/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties/new'
import { Route as AuthenticatedPropertiesIdEditRouteImport } from './routes/_authenticated/properties/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdEditRoute =
  AuthenticatedPropertiesIdEditRouteImport.update({
    id: '/properties/$id/edit',
    path: '/properties/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/properties/new'
    | '/properties/'
    | '/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/properties/new'
    | '/properties'
    | '/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties/new'
    | '/_authenticated/properties/'
    | '/_authenticated/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/edit': {
      id: '/_authenticated/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedPropertiesIdEditRoute: typeof AuthenticatedPropertiesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedPropertiesIdEditRoute: AuthenticatedPropertiesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
